Deprecate project
SAP/openui5-worklist-app pull request #81
Opened 2023-06-02 11:12 UTC by flovogt

Add deprecation info to README.md

2024-10-14 06:46 UTC, KlattG requested changes

2024-10-14 06:46 UTC, KlattG commented on README.md
> +**⚠️ This project has been deprecated in favor of [OpenUI5 Sample App](https://github.com/SAP/openui5-sample-app) and [Worklist App Tutorial](https://ui5.sap.com/#/topic/6a6a621c978145ad9eef2b221d2cf
```suggestion
**⚠️ This project has been deprecated in favor of our [OpenUI5 Sample App](https://github.com/SAP/openui5-sample-app) and the [Worklist App Tutorial](https://ui5.sap.com/#/topic/6a6a621c978145ad9eef2b221d2cf21d).**
```

2024-10-17 09:43 UTC, KlattG approved these changes
LGTM

2024-11-04 08:17 UTC, matz3 approved these changes

2024-11-04 08:20 UTC, merged